version: '3'

volumes:
  prometheus: {}
  grafana: {}

networks:
  public: {}
  routable: {}
  monitoring: {}
  observability: {}

services:

  nodeexporter:
    image: quay.io/prometheus/node-exporter:latest
    hostname: nodeexporter
    container_name: nodeexporter
    command:
      - '--path.rootfs=/host'
      - '--collector.disable-defaults'
      - '--collector.cpu'
      - '--collector.loadavg'
      - '--collector.diskstats'
      - '--collector.filesystem'
      - '--collector.meminfo'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    ports:
      - 9100:9100
    networks:
      - monitoring

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./aqm/aqi.rules.yml:/etc/prometheus/aqi.rules.yml
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
      - '--storage.tsdb.retention.time=5y'
    ports:
      - 9090:9090
    restart: unless-stopped
    labels: 
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.local`)"
    networks:
      - monitoring
      - routable
      - observability

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    volumes:
      - ./grafana/config.ini:/etc/grafana/config.ini
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/default.yaml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./aqm/dashboard.json:/var/lib/grafana/dashboards/aqm_dashboard.json
      - ./node-exporter/dashboard.json:/var/lib/grafana/dashboards/node_dashboard.json
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    labels: 
      - "traefik.http.routers.grafana.rule=Host(`grafana.local`)"
    networks:
      - routable
      - observability

  shairport:
    container_name: shairport
    image: mikebrady/shairport-sync
    restart: unless-stopped
    devices:
      - /dev/snd
    network_mode: host
    privileged: true
    command:
      - '--'
      - '-c PCM'

  reverse-proxy:
    container_name: reverse-proxy
    image: traefik:v2.7
    restart: unless-stopped
    command: 
      - '--api.insecure=true'
      - '--providers.docker'
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - public
      - routable

  mdns-publisher:
    container_name: mdns-publisher
    build: ./mdns-publisher
    network_mode: host
    environment:
      TRAEFIK_API_HOST: 'http://localhost:8080'
      BINDING_IP_ADDRESS: '192.168.1.8'
      POLL_INTERVAL: '30000'
    volumes:
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
    restart: unless-stopped

