version: '3'

volumes:
  prometheus: {}
  grafana: {}

services:

  nodeexporter:
    image: quay.io/prometheus/node-exporter:latest
    hostname: nodeexporter
    container_name: nodeexporter
    command:
      - '--path.rootfs=/host'
      - '--collector.disable-defaults'
      - '--collector.cpu'
      - '--collector.loadavg'
      - '--collector.diskstats'
      - '--collector.filesystem'
      - '--collector.meminfo'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    ports:
      - 9100:9100

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./aqi.rules.yml:/etc/prometheus/aqi.rules.yml
      - prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
      - '--storage.tsdb.retention.time=5y'
    ports:
      - 9090:9090
    restart: unless-stopped

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    volumes:
      - ./grafana_config.ini:/etc/grafana/config.ini
      - ./grafana_datasources.yml:/etc/grafana/provisioning/datasources/default.yaml
      - ./grafana_dashboards.yml:/etc/grafana/provisioning/dashboards/default.yaml
      - ./dashboard.json:/var/lib/grafana/dashboards/aqm_dashboard.json
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000
    restart: unless-stopped

  shairport:
    container_name: shairport
    image: mikebrady/shairport-sync
    restart: unless-stopped
    devices:
      - /dev/snd
    network_mode: host
    command:
      - '-d hw:0'
      - '-c PCM'
