{
 "title": "AQM",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Previous 24h PM2.5 Air Quality Index",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aqi:24h", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Nowcast PM2.5 Air Quality Index",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aqi:nowcast", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aqm_temperature_degf{sensor=\"scd\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(aqm_humidity_percentage{sensor=\"scd\"}[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CO₂ PPM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    { "expr": "aqm_co2_ppm", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Raw Measurements",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Particulate Matter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "avg_over_time(aqm_particulate_matter[3m])",
     "legendFormat": "PM {{size}}, {{host}}"
    }
   ]
  },
  {
   "title": "Atmospheric Pressure",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "expr": "avg_over_time(aqm_pressure_pa[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Gas Resistance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ohm" } },
   "targets": [
    {
     "expr": "avg_over_time(aqm_gas_ohms[1m])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Recording Success",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(aqm_recording_success[1m])) / \n(sum(irate(aqm_recording_success[1m])) + sum(irate(aqm_recording_error[1m]) or vector(0)))",
     "legendFormat": "Success"
    }
   ]
  }
 ]
}